SHELL = cmd.exe

#
# ZDS II Make File - CPM30, Debug_Platform
#
# Generated by: ZDS II - eZ80Acclaim! 4.10.1 (Build 06092501)
#   IDE component: b:4.10:06092301
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_4.10.1\
#

CC = @C:\PROGRA~1\ZiLOG\ZDSII_~1.1\bin\eZ80cc
ASM = @C:\PROGRA~1\ZiLOG\ZDSII_~1.1\bin\eZ80asm
LINK = @C:\PROGRA~1\ZiLOG\ZDSII_~1.1\bin\eZ80link
LIB = @C:\PROGRA~1\ZiLOG\ZDSII_~1.1\bin\eZ80lib
WEBTOC = @C:\PROGRA~1\ZiLOG\ZDSII_~1.1\bin\mkwebpage
FIXSEG = @C:\PROGRA~1\ZiLOG\ZDSII_~1.1\bin\fixseg.bat


CFLAGS =  \
-define:_EZ80F91 -define:_EZ80ACCLAIM! -genprintf -keepasm  \
-keeplst -NOlist -NOlistinc -modsect -optsize -promote -reduceopt  \
-stdinc:"C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\std;C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog"  \
-warn -debug -cpu:EZ80F91  \
-asmsw:" -cpu:EZ80F91 -define:_EZ80ACCLAIM!=1 -define:_DEBUG -define:_PLT -include:C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\std;C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog" \
-noasm

AFLAGS =  \
-define:_EZ80ACCLAIM!=1 -define:_DEBUG -define:_PLT  \
-include:"C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\std;C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog"  \
-list -NOlistmac -name -pagelen:56 -pagewidth:80 -quiet -sdiopt  \
-warn -debug -NOigcase -cpu:EZ80F91

OUTDIR = 

build: CPM30

rebuildall: clean CPM30

relink: deltarget CPM30

deltarget: 
	@if CPM30_PLT.lod  \
            del CPM30_PLT.lod
	@if CPM30_PLT.hex  \
            del CPM30_PLT.hex
	@if CPM30_PLT.map  \
            del CPM30_PLT.map

clean: 
	@if CPM30_PLT.lod  \
            del CPM30_PLT.lod
	@if CPM30_PLT.hex  \
            del CPM30_PLT.hex
	@if CPM30_PLT.map  \
            del CPM30_PLT.map
	    del *.obj
	    del *.src

LIBS = 

OBJS =  \
            flashdsk.obj  \
            BDOS713.obj  \
            BOOT.obj  \
            SCB.obj  \
            MOVE.obj  \
            DRVTBL.obj  \
            flashdrv.obj  \
            init_params_f91.obj  \
            CCP3.obj  \
            LOADER3.obj  \
            eZ80-CPM-MMC.obj  \
            eZ80-CPM-DEBUG.obj  \
            sdmmcdrv.obj  \
            cbios.obj  \
            CTBL.obj  \
            CBIOSKRNL.obj  \
            sdmem.obj

CPM30: $(OBJS)
	 $(LINK)  @CPM30.linkcmd

flashdsk.src :  \
            flashdsk.c
	 $(CC)  $(CFLAGS) flashdsk.c

BDOS713.obj :  \
            BDOS713.ASM  \
            cpm3_defs.inc
	 $(ASM)  $(AFLAGS) BDOS713.ASM

BOOT.obj :  \
            BOOT.ASM  \
            SCB.ASM  \
            cpm3_defs.inc  \
            ..\..\shared\eZ80F91_Regs.inc
	 $(ASM)  $(AFLAGS) BOOT.ASM

SCB.obj :  \
            SCB.ASM
	 $(ASM)  $(AFLAGS) SCB.ASM

MOVE.obj :  \
            MOVE.ASM  \
            cpm3_defs.inc
	 $(ASM)  $(AFLAGS) MOVE.ASM

DRVTBL.obj :  \
            DRVTBL.ASM  \
            cpm3_defs.inc
	 $(ASM)  $(AFLAGS) DRVTBL.ASM

flashdrv.obj :  \
            flashdrv.asm  \
            cpm3_defs.inc
	 $(ASM)  $(AFLAGS) flashdrv.asm

init_params_f91.obj :  \
            ..\..\shared\init_params_f91.asm  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\ez80F91.inc
	 $(ASM)  $(AFLAGS) ..\..\shared\init_params_f91.asm

CCP3.obj :  \
            CCP3.ASM  \
            cpm3_defs.inc
	 $(ASM)  $(AFLAGS) CCP3.ASM

LOADER3.obj :  \
            LOADER3.ASM  \
            cpm3_defs.inc
	 $(ASM)  $(AFLAGS) LOADER3.ASM

eZ80-CPM-MMC.obj :  \
            ..\..\shared\eZ80-CPM-MMC.asm  \
            ..\..\shared\eZ80F91_Regs.inc
	 $(ASM)  $(AFLAGS) ..\..\shared\eZ80-CPM-MMC.asm

eZ80-CPM-DEBUG.obj :  \
            ..\..\shared\eZ80-CPM-DEBUG.asm
	 $(ASM)  $(AFLAGS) ..\..\shared\eZ80-CPM-DEBUG.asm

sdmmcdrv.obj :  \
            sdmmcdrv.asm  \
            cpm3_defs.inc
	 $(ASM)  $(AFLAGS) sdmmcdrv.asm

cbios.src :  \
            cbios.c  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\defines.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\eZ80190.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\eZ80F91.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\eZ80F92.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\eZ80F93.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\eZ80L92.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\ez80.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\gpio.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\uart.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\uartdefs.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\eZ80F91.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\ez80.h  \
            modebaud.h
	 $(CC)  $(CFLAGS) cbios.c

CTBL.obj :  \
            CTBL.ASM  \
            MODEBAUD.INC
	 $(ASM)  $(AFLAGS) CTBL.ASM

CBIOSKRNL.obj :  \
            CBIOSKRNL.ASM  \
            SCB.ASM  \
            cpm3_defs.inc  \
            ..\..\shared\eZ80F91_Regs.inc
	 $(ASM)  $(AFLAGS) CBIOSKRNL.ASM

sdmem.src :  \
            ..\..\shared\sdmem.c  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\std\Format.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\std\Stdarg.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\std\Stdio.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\defines.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\eZ80190.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\eZ80F91.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\eZ80F92.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\eZ80F93.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\eZ80L92.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\ez80.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\gpio.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\uart.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\uartdefs.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\std\Stdio.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\std\String.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\eZ80F91.h  \
            C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include\zilog\ez80.h  \
            ..\..\shared\sdmem.h
	 $(CC)  $(CFLAGS) ..\..\shared\sdmem.c

cbios.obj : cbios.src
	 $(FIXSEG) cbios
	 $(ASM)  $(AFLAGS) cbios.src

sdmem.obj : sdmem.src
	 $(FIXSEG) sdmem
	 $(ASM)  $(AFLAGS) sdmem.src

flashdsk.obj : flashdsk.src
	 $(FIXSEG) flashdsk
	 $(ASM)  $(AFLAGS) flashdsk.src


